#!/bin/sh

# setup for multiple monitors
i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor \
		-n "$i" \
		-d $i/{I II III IV V VI}
	let i++
done
NMON=$i
unset i


# visual options
bspc config top_padding                 25
bspc config split_ratio                 0.50
bspc config border_width                2
bspc config window_gap                  4
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config auto_alternate              true
bspc config auto_cancel                 true
bspc config normal_border_color         "#504339"
bspc config active_border_color         "#504339"
bspc config focused_border_color        "#817267"
bspc config presel_border_color         "#9a875f"
bspc config urgent_border_color         "#504339"
bspc config focused_locked_border_color "#8c644c"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1


# application rules
bspc rule -a Gimp desktop=^5 state=floating follow=on
bspc rule -a feh state=floating manage=off
bspc rule -a mpv state=floating

# launch polybar
/home/soma/.config/polybar/launch.sh &
