#!/bin/ruby

require_relative './lib/xresources_accessor'

def change_color(color)
    accessor = Xresources_Accessor.new
    lines = edit_xresources(color, accessor.path)
    accessor.create_tmp_xresources(accessor.path, lines)
end

def edit_xresources(color, path)
    IO.readlines(path).map do |line|
        edit_color_lines(line, color) || line
    end
end

def edit_color_lines(line, color)
    return line.gsub('!','') if line =~ /!#include.*#{color}/
    line.prepend('!') if line =~ /^#include/
end

change_color(ARGV.first)
